# 配置项目端口号
server:
  port: 8100
  servlet:
    context-path: /optimus_visual
    encoding:
      charset: UTF-8
      enabled: true
      force: true #在HTTP请求和响应中强制编码为已配置的字符集。(UTF-8)?

# Spring 配置
spring:
  application:
    name: optimus_visual
  datasource:
    #数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.128.3.29:3306/optimus_visual?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: Unisound@123
      initial-size: 3
      max-active: 20
      min-idle: 5
  #用于解决swagger3.0.0和spring boot2.6.3兼容问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml #绑定xml文件
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus打印日志的替换方案,只打印执行的sql和返回结果条数而不打印返回结果集
logging:
  level:
    com:
      unisound:
        medical:
          sdraux:
            mapper: debug

elasticsearch:
  host: 10.128.3.122
  port: 9200
  eventNames: admission,death,leave,discharge,identity,profile,CT,MRI,bacilliculture,rescue,chemotherapy,bloodTransfusion,antibiotic,implant,radiotherapy,pathologic,surgery,procedure,diagnosis,transferred,seriouslyIll,gestation,deliver
  search:
    paths: docs,nodes,chd
    pathsField: docType,name

#文书显示节点黑名单,多个用逗号隔开
NodeShowBlackList: 一般情况,既往史
#设置黑名单的文书,多个用逗号隔开,如果为空则表示对所有文书生效
UseBlackListOnDocList: EMR090001

#BaseResourceUrl: D:\wyd\dev_projects\optimus_visual\backend\base_resource
BaseResourceUrl: D:\wyd\dev_projects\github_project\optimus_visual\backend\base_resource
#BaseResourceUrl: /blzk/optimus_visual/base_resource




